import js from '@eslint/js';
import globals from 'globals';

const STATIC_SHARED_GLOBALS = {
  $: 'writable',
  apiJSON: 'writable',
  applyCompareFormState: 'writable',
  applySearchState: 'writable',
  buildCompareFormState: 'writable',
  changePage: 'writable',
  clearCompareBusy: 'writable',
  closeModal: 'writable',
  compareDbState: 'writable',
  currentFlow: 'writable',
  doSearch: 'writable',
  escapeAttr: 'writable',
  escapeHtml: 'writable',
  exportResultsCsv: 'writable',
  fetchServerLogs: 'writable',
  filesPanelOpen: 'writable',
  forceCloseModals: 'writable',
  formatBytes: 'writable',
  getCompareFormRefs: 'writable',
  getFlowFromName: 'writable',
  guessKeyColumnsForTable: 'writable',
  hasDbSelected: 'writable',
  isBlankCompareValue: 'writable',
  isFileAllowedForFlow: 'writable',
  lastQuery: 'writable',
  lastResults: 'writable',
  lastStatus: 'writable',
  lastUploads: 'writable',
  loadPriorityModal: 'writable',
  logUi: 'writable',
  manualFlowOverride: 'writable',
  normalizeFlow: 'writable',
  openModalById: 'writable',
  openTable: 'writable',
  postJson: 'writable',
  priorityTables: 'writable',
  refreshStatus: 'writable',
  refreshTables: 'writable',
  refreshUiState: 'writable',
  renderDbTabs: 'writable',
  renderFilesMain: 'writable',
  renderFilesSelect: 'writable',
  renderResult: 'writable',
  renderResults: 'writable',
  renderSelectedInfo: 'writable',
  renderStatusModal: 'writable',
  resetAdvancedDefaults: 'writable',
  resetFlowToInitial: 'writable',
  restoreFromSavedState: 'writable',
  saveCompareState: 'writable',
  savePriority: 'writable',
  scheduleStatusPoll: 'writable',
  setButtonBusy: 'writable',
  setCompareBusy: 'writable',
  setCompareStatus: 'writable',
  setFilesPanelOpen: 'writable',
  setFlow: 'writable',
  setFlowBanner: 'writable',
  setFlowHint: 'writable',
  setModalBanner: 'writable',
  setStepOpen: 'writable',
  setStepState: 'writable',
  setUploadStatus: 'writable',
  setupBootstrapGlobalHandlers: 'writable',
  setupCompareUploadBindings: 'writable',
  setupFilePanelBindings: 'writable',
  setupFlowBindings: 'writable',
  setupIndexBindings: 'writable',
  setupModalBindings: 'writable',
  setupSearchBindings: 'writable',
  setupUploadBindings: 'writable',
  shortName: 'writable',
  shortValue: 'writable',
  showRowSegment: 'writable',
  tableTagId: 'writable',
  updateCompareValueSignals: 'writable',
  updateLastCompareMeta: 'writable',
  updateRowLimitState: 'writable',
  updateTablesOverviewVisibility: 'writable',
  valuesDifferent: 'writable',
};

export default [
  {
    ignores: [
      'interface/uploads/**',
      'output/**',
      'node_modules/**',
      'bkp_limpeza/**',
      '.venv/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['static/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...STATIC_SHARED_GLOBALS,
      },
    },
    rules: {
      'no-empty': 'off',
      'no-undef': 'warn',
      'no-redeclare': 'off',
      'no-useless-assignment': 'off',
      'no-unused-vars': 'off',
      'no-var': 'off',
      'prefer-const': 'off',
    },
  },
];
